application: bb-oftl-hrd
version: 9
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /submitter/OFTLSubmitter.py
  static_files: grappl/OFTLSubmitter.py
  upload: grappl/OFTLSubmitter.py

- url: /submitter/OFTL-submitter.py
  static_files: grappl/OFTL-submitter.py
  upload: grappl/OFTL-submitter.py

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css


- url: /parent_refresh
  static_files: static/parent_refresh.html
  upload: static/parent_refresh.html

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /cron/*
  script: main.py
  login: admin
  
- url: .*
  script: main.py

libraries:
- name: django
  version: "1.4"

builtins:
- django_wsgi: on
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*